image:  epitechcontent/epitest-docker

stages:
    - build
    - tests
    - norme

job:build:
    stage: build
    script:
        - make fclean
        - make re
        - make

job:tests:
    stage: tests
    script:
        - make
        - echo $RETURN
        - RETURN = 'tests/git_minishell_tests.sh'
        - echo $RETURN

job:norme:
    stage: norme
    script:
        - tests/NormEZ.rb
        - make fclean
    allow_failure : true
